include:
  - project: 'famedly/infra/templates/ci-cd'
    ref: rust-v1
    file:
      - '/rust.yml'
  - project: 'famedly/infra/templates/ci-cd'
    ref: docker-v1
    file:
      - '/docker.yml'

stages:
  - test
  - deploy

cargo-check:
  extends: .cargo_check
  variables:
    DATABASE_URL: "postgres://baraddur:baraddur@postgres/baraddur"
    POSTGRES_DB: baraddur
    POSTGRES_USER: baraddur
    POSTGRES_PASSWORD: "baraddur"
    POSTGRES_HOST_AUTH_METHOD: trust
  services:
    - name: docker.io/postgres:15-alpine
      alias: postgres
  script:
    - sqlx migrate run
    - cargo sqlx prepare --check -- --all-targets --all-features
    - !reference [.cargo_check, script]

docker-releases:
  extends: .docker_releases

docker-tags:
  extends: .docker_tags

docker-branches:
  extends: .docker_branches
