CREATE TABLE IF NOT EXISTS aggregated_stats
(
    day date PRIMARY KEY,
    total_users BIGINT,
    total_nonbridged_users BIGINT,
    total_room_count BIGINT,
    daily_active_users BIGINT,
    daily_active_rooms BIGINT,
    daily_messages BIGINT,
    daily_sent_messages BIGINT,
    daily_active_e2ee_rooms BIGINT,
    daily_e2ee_messages BIGINT,
    daily_sent_e2ee_messages BIGINT,
    monthly_active_users BIGINT,
    r30_users_all BIGINT,
    r30_users_android BIGINT,
    r30_users_ios BIGINT,
    r30_users_electron BIGINT,
    r30_users_web BIGINT,
    r30v2_users_all BIGINT,
    r30v2_users_android BIGINT,
    r30v2_users_ios BIGINT,
    r30v2_users_electron BIGINT,
    r30v2_users_web BIGINT,
    daily_user_type_native BIGINT,
    daily_user_type_bridged BIGINT,
    daily_user_type_guest BIGINT,
    daily_active_homeservers BIGINT
);
