name: "Docker"

on:
  push:
    branches: [ "main" ]
    tags: [ "*" ]

jobs:
  build:
    uses: famedly/backend-build-workflows/.github/workflows/docker-backend.yml@v3
    secrets: inherit
    with:
      targets: barad-dur
      oss: true
