name: Rust

on:
  push:
    branches: [ "main" ]
    tags: [ "*" ]
  pull_request:
    branches: [ "*" ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref}}
  cancel-in-progress: true

env:
  CARGO_TERM_COLOR: always
  DATABASE_URL: "postgresql://postgres:password@postgres:5432/baraddur"
  SQLX_OFFLINE: "true"
jobs:
  check:
    runs-on: ubuntu-latest
    container: registry.famedly.net/docker-oss/rust-container:nightly
    name: Formatting, lints, syntax, and typos
    steps:
      - uses: actions/checkout@v4
      - uses: famedly/backend-build-workflows/.github/actions/rust-prepare@main
        with:
          gitlab_user: ${{ secrets.GITLAB_USER }}
          gitlab_pass: ${{ secrets.GITLAB_PASS }}
          gitlab_ssh: ${{ secrets.CI_SSH_PRIVATE_KEY}}

      - name: Caching
        uses: Swatinem/rust-cache@65012b490220f477f20ab979e35ae732e6de4e68
        with:
          shared-key: "stable"

      - name: Typos
        uses: crate-ci/typos@7b04f660f4ee4f048d18fd341887cf28dfbedfe2

      - name: Check
        shell: bash
        env:
          SQLX_OFFLINE: "true"
        run: |
          cargo +${NIGHTLY_VERSION} fmt -- --check
          cargo clippy --workspace --all-targets -- -D warnings

  test:
    runs-on: ubuntu-latest
    container: registry.famedly.net/docker-oss/rust-container:nightly
    name: Tests and coverage
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_PASSWORD: password
          POSTGRES_USER: postgres
          POSTGRES_DB: baraddur
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
      - uses: actions/checkout@v4

      - uses: famedly/backend-build-workflows/.github/actions/rust-prepare@main
        with:
          gitlab_user: ${{ secrets.GITLAB_USER }}
          gitlab_pass: ${{ secrets.GITLAB_PASS }}
          gitlab_ssh: ${{ secrets.CI_SSH_PRIVATE_KEY}}

      - name: Caching
        uses: Swatinem/rust-cache@65012b490220f477f20ab979e35ae732e6de4e68
        with:
          shared-key: "stable"

      - name: Test
        shell: bash
        run: |
          sqlx migrate run
          cargo sqlx prepare --check -- --all-targets --all-features
          cargo llvm-cov nextest --profile ci --workspace --lcov --output-path lcov.info

      - name: Codecov - Upload coverage
        uses: codecov/codecov-action@ca0a928a4cb3911011e868128a5cd90437c12db1
        with:
          token: ${{secrets.CODECOV_TOKEN}}
          files: "lcov.info"

      - name: Codecov - Upload test results
        uses: codecov/test-results-action@0fa95f0e1eeaafde2c782583b36b28ad0d8c77d3
        with:
          token: ${{secrets.CODECOV_TOKEN}}

  doc-test:
    runs-on: ubuntu-latest
    container: ghcr.io/famedly/rust-container:nightly
    name: Documentation tests
    steps:
      - uses: actions/checkout@v4
      - uses: famedly/backend-build-workflows/.github/actions/rust-prepare@main
        with:
          gitlab_user: ${{ secrets.GITLAB_USER }}
          gitlab_pass: ${{ secrets.GITLAB_PASS }}
          gitlab_ssh: ${{ secrets.CI_SSH_PRIVATE_KEY}}

      - name: Caching
        uses: Swatinem/rust-cache@65012b490220f477f20ab979e35ae732e6de4e68
        with:
          shared-key: "nightly"

      - name: Documentation tests
        shell: bash
        env:
          SQLX_OFFLINE: "true"
        run: |
          cargo +${NIGHTLY_VERSION} test --doc --workspace --verbose

  udeps:
    runs-on: ubuntu-latest-16core
    container: ghcr.io/famedly/rust-container:nightly
    name: Unused dependencies
    steps:  
      - uses: actions/checkout@v3
      - uses: famedly/backend-build-workflows/.github/actions/rust-prepare@main
        with:
          gitlab_user: ${{ secrets.GITLAB_USER }}
          gitlab_pass: ${{ secrets.GITLAB_PASS }}
          gitlab_ssh: ${{ secrets.CI_SSH_PRIVATE_KEY}}

      - name: Caching
        uses: Swatinem/rust-cache@65012b490220f477f20ab979e35ae732e6de4e68
        with:
          shared-key: "nightly"

      - name: Unused dependencies
        shell: bash
        env:
          SQLX_OFFLINE: "true"
        run: |
          cargo +${NIGHTLY_VERSION} udeps
